version: "3"

services:
  front:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./Front:/usr/share/nginx/html
  back:
    image: openjdk
    ports:
      - "8081:81"
    volumes:
      - ./Back:/app
    command: sh /app/run.sh