version: "3"

services:
  client:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./Client:/usr/share/nginx/html
  server:
    image: openjdk
    ports:
      - "8081:81"
    volumes:
      - ./Server:/app
    command: sh /app/run.sh