version: "3"

services:
  front:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./Front:/usr/share/nginx/html
  back:
    image: maven
    ports:
      - "8081:81"
    volumes:
      - ./Back/java:/app
    command: sh /app/run.sh
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql
    ports:
      - 8082:3306
    environment:
      MYSQL_ROOT_PASSWORD: g7Nn5DkEBLCbpCTNw84FPkw3wjoDPYu4KJ2NSSkb
    volumes:
      - ./Back/mysql:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080