version: "3"

services:
  client:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./src/Client:/usr/share/nginx/html
  server:
    image: java
    ports:
      - "8081:81"
    volumes:
      - ./src/Client:/app