version: "3"

services:
  front:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./Front:/usr/share/nginx/html
  back:
    image: openjdk
    ports:
      - "8081:81"
    volumes:
      - ./Back:/app
    command: sh /app/run.sh
  db:
    image: mongo
    ports:
      - "8082:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: NEkzsqPkAwEqC82FTM9VEerHBw7WvNjeKwpqDkhp